In [1]:
import numpy as np
#pandas creating data frames =structured table
import pandas as pd
#split data into testing and training data 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#evaluate model"s performance
from sklearn.metrics import accuracy_score

In [2]:
#data collection
data=pd.read_csv("heart_disease_data.csv")

In [3]:
#data 5first elements
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
#data 5last elements
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
#number of lignes and columns
data.shape

(303, 14)

In [6]:
#information about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [7]:
#checking missing values (we can handle the missing value by a process called imputation)
data.isnull().sum()
#data.notnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
#statistical mesures about the data
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [9]:
#checking the distribution of target variables
data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

0 --> Defective heart /n

1 --> healthy heart

In [10]:
#splitting the features and targets
x=data.drop(columns="target",axis=1)
y=data["target"]
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [11]:
#splitting data into test and training data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)
y_test.shape

(61,)

In [12]:
#training the Model
model=LogisticRegression(solver='lbfgs', max_iter=1000)

In [13]:
#training the model 
model.fit(x_train , y_train ,)

LogisticRegression(max_iter=1000)

In [14]:
#model evaluation


#accuracy on trainig data
x_train_prediction=model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [15]:
print("accuracy_score on training data",training_data_accuracy)
#85%  correct data

accuracy_score on training data 0.8553719008264463

In [16]:
#accuracy on test data
x_test_prediction=model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [17]:
print("accuracy_score on testing data",testing_data_accuracy)

accuracy_score on testing data 0.8032786885245902

Predicting

In [18]:

#first method
 #input is a tuple
input_data=(58,1,0,100,234,0,1,156,0,0.1,2,1,3)
#tuple to numpy to reshape
input_data_as_array=np.asarray(input_data)
#reshape to predict only one value else the model will predict 242 value (the trainig data)
reshaped_input_data=input_data_as_array.reshape(1,-1)
print(reshaped_input_data)

 #2nd method
 #  reshaped_input_data=np.array([[58,1,0,100,234,0,1,156,0,0.1,2,1,3]])


#build a predicition 
prediction=model.predict(reshaped_input_data)
print(prediction)
if prediction[0]==1:
    print("the person has heart disease")
else:
    print("the person does not have heart disease")

[[5.80e+01 1.00e+00 0.00e+00 1.00e+02 2.34e+02 0.00e+00 1.00e+00 1.56e+02
  0.00e+00 1.00e-01 2.00e+00 1.00e+00 3.00e+00]]
[0]
the person does not have heart disease

c:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [19]:
import pickle
file="trained_model.sav"
pickle.dump(model,open(file,"wb")) #wb write in binary

In [20]:
#loading the saved model
loaded_model=pickle.load(open(file,"rb"))

In [21]:
input_data=(58,1,0,100,234,0,1,156,0,0.1,2,1,3)
#tuple to numpy to reshape
input_data_as_array=np.asarray(input_data)
#reshape to predict only one value else the model will predict 242 value (the trainig data)
reshaped_input_data=input_data_as_array.reshape(1,-1)
print(reshaped_input_data)

 #2nd method
 #  reshaped_input_data=np.array([[58,1,0,100,234,0,1,156,0,0.1,2,1,3]])


#build a predicition 
prediction=loaded_model.predict(reshaped_input_data)
print(prediction)
if prediction[0]==1:
    print("the person has heart disease")
else:
    print("the person does not have heart disease")

[[5.80e+01 1.00e+00 0.00e+00 1.00e+02 2.34e+02 0.00e+00 1.00e+00 1.56e+02
  0.00e+00 1.00e-01 2.00e+00 1.00e+00 3.00e+00]]
[0]
the person does not have heart disease

c:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(